defaults:
  data_dir: data
  tipo_imagen: MCMI
  satelite: GOES16
  png_conf:
    out_dir: salidas
  geotiff_conf:
    out_dir: geotiffs
jobs:
- nombre: demo
  tipo_imagen: MCMI
  productos:
  - air_mass
  salidas:
  - PNG
  - GeoTIFF
  satelite: GOES16
  datetime: '2025-08-30T18:00:00'
  geotiff_conf:
    out_dir: geotiffs/
    filename_pattern: '{producto}_{ts}.tif'
    producto: air_mass
