# environment.yml
name: goes-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - s3fs
  - xarray
  - netCDF4
  - boto3
  - matplotlib
  - numpy
  - scipy
  - pandas
  - ipykernel
  - jupyter
  # ...otras dependencias...
  - pip
  - pip:
      - -e .