defaults:
  tipo_imagen: MCMI
  recorte: [-0.02, -18.2, -81.79, -68.0]
  export:
    out_dir: salidas/
    shapefile_provincias: shapefiles/provincias/linea_de_limite_070111Line.shp
    show: false

jobs:
  - nombre: peru_color_real
    satelite: GOES19
    datetime: 2024-12-30T15:00:00
    productos: [true_color]

  - nombre: peru_daily_microphysics
    satelite: GOES19
    datetime: 2024-12-30T15:00:00
    productos: [daily_microphysics]