defaults:
  tipo_imagen: MCMI
  satelite: GOES16
  data_dir: data/
  recorte:
    - -18.6
    - -56.45
    - -79.79
    - -50
  export:
    out_dir: salidas/
    show: false
jobs:
  - productos:
      - true_color
    salidas:
      - PNG
